### PR TITLE
Ensure MI is in increasing order

### PR DESCRIPTION
**Pull request by nh13**

### CODE REVIEW

**Comment by nh13** [comment]
@tfenne curious about what you think.

**Comment by nh13** [comment]
@tfenne https://www.youtube.com/watch?v=8lYBVi3ALWA

**Comment by nh13** [comment]
@tfenne I updated based on your suggestion.  Lets just hope that the first few groups are OK, since this solution _doesn't_ work if the first 100 reads are grouped (i.e. `seq 1 100 | sort` vs `seq 1 100 | sort -n`)

**Comment by tfenne** [comment]
👍  I'm not sure I understand your comment about 1-100 though.

**Pull request merged**
